// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutPopover: typeof import('@nutui/nutui-taro')['Popover']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    NutTour: typeof import('@nutui/nutui-taro')['Tour']
  }
}
